version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - URL_DATABASE=mongodb://database:27017/Social_media
      - SECRETE_KEY_TOKEN=abc
    ports:
      - 8000:8000
  database:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=Social_media